# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: Deployment

on:
  push:
    branches: [ master ]
    
env:
  BUCKET_NAME : "2-dev-jp-001"
  AWS_REGION : "ap-southeast-2"
  AWS_ROLE_ARN: arn:aws:iam::891707123434:role/AAA-Github-Role-EC2FullAccess

jobs:
  check-aws-access:
    permissions: # permission can be added at job level or workflow level    
      contents: read # for actions/checkout to fetch code
      id-token: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: check-aws-access
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: provision/aws/terraform-scripts

    steps:
      - name: Clone the current github repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}-${{ github.run_number }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Copy index.html to S3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
  
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

  static-code-analysis:
    permissions: # permission can be added at job level or workflow level    
      contents: read
      security-events: write
    name: static-code-analysis
    environment: dev
    runs-on: ubuntu-latest
    needs: check-aws-access
    steps:
      - name: Clone the current github repo
        uses: actions/checkout@v3
      
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true 
          # Include your own basic security rules. Removing this option will run all the rules 
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif